apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.project.name }}
  namespace: istio-system
spec:
  secretName: {{ .Values.project.name }}-tls
  issuerRef:
    name: letsencrypt
  dnsNames:
  - "*.{{ .Values.project.domain }}"