apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-90"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: csi
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.targetRevision }}
    helm:
      valueFiles:
        - ../apps/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true