apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: {{ .Values.metadata.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: logging-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: loki
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - ../apps/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true