apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-domains
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cert-manager/cert-manager-domains
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.targetRevision }}
    helm:
      valueFiles:
        - ../../apps/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true